variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

before_script:
  - 'mvn --batch-mode --non-recursive -q io.takari:maven:wrapper -Dmaven=3.3.9'

.jdk_validate: &jdk_validate
  stage: build
  script:
    - './mvnw --show-version --errors --batch-mode test-compile'
  artifacts:
    paths:
      - "./*/target/*"

.jdk_test: &jdk_test
  stage: test
  script:
    - './mvnw --show-version --errors --batch-mode -DskipITs verify site'

validate:jdk7:
  <<: *jdk_validate
  image: maven:3-jdk-7

validate:jdk8:
  <<: *jdk_validate
  image: maven:3-jdk-8

test:jdk7:
  <<: *jdk_test
  image: maven:3-jdk-7
  dependencies:
    - validate:jdk7

test:jdk8:
  <<: *jdk_test
  image: maven:3-jdk-8
  dependencies:
    - validate:jdk8
